use [BD_HISINDICADORES]

drop table dbo.PN_MAYO_2025
CREATE TABLE dbo.PN_MAYO_2025 (
    NRO INT,
    TIPO_DOCUMENTO VARCHAR(50),
    COD_PAD VARCHAR(50),
    CNV VARCHAR(50),
    CUI VARCHAR(50),
    DNI VARCHAR(15),
    ESTADO_DE_TRAMITE_DNI VARCHAR(100),
    FECHA_DE_TRAMITE_DNI VARCHAR(100),
    APELLIDO_PATERNO VARCHAR(100),
    APELLIDO_MATERNO VARCHAR(100),
    NOMBRE_NINO VARCHAR(200),
    SEXO CHAR(1),
    FECHA_NACIMIENTO VARCHAR(200),
    EDAD_LETRAS VARCHAR(50),
    EJE_VIAL VARCHAR(100),
    DESCRIPCION VARCHAR(255),
    REFERENCIA_DIRECCION VARCHAR(255),
    LATITUD VARCHAR(30),
    LONGITUD VARCHAR(30),
    COD_UBIGEO VARCHAR(10),
    DEPARTAMENTO VARCHAR(50),
    PROVINCIA VARCHAR(50),
    DISTRITO VARCHAR(50),
    CODIGO_CENTRO_POBLADO VARCHAR(50),
    CENTRO_POBLADO VARCHAR(100),
    AREA_CENTRO_POBLADO VARCHAR(50),
    MENOR_VISITADO VARCHAR(100),
    MENOR_ENCONTRADO VARCHAR(10),
    FECHA_VISITA VARCHAR(100),
    FUENTE_DATOS VARCHAR(100),
    FECHA_FUENTE_DATOS VARCHAR(100),
    CODIGO_NACIMIENTO VARCHAR(50),
    NOMBRE_NACIMIENTO VARCHAR(100),
    CODIGO_EESS VARCHAR(50),
    NOMBRE_EESS VARCHAR(150),
    FRECUENCIA_ATENCION VARCHAR(50),
    CODIGO_EESS_ADSCRIPCION VARCHAR(50),
    NOMBRE_EESS_ADSCRIPCION VARCHAR(150),
    TIPO_SEGURO VARCHAR(50),
    PROGRAMAS_SOCIALES VARCHAR(150),
    CODIGO_INSTITUCION_EDUCATIVA VARCHAR(50),
    NOMBRE_INSTITUCION_EDUCATIVA VARCHAR(200),
    RELACION VARCHAR(50),
    TIPO_DE_DOCUMENTO_DE_LA_MADRE VARCHAR(50),
    DNI_MADRE VARCHAR(15),
    APELLIDO_PATERNO_MADRE VARCHAR(100),
    APELLIDO_MATERNO_MADRE VARCHAR(100),
    NOMBRES_MADRE VARCHAR(150),
    NUMERO_CELULAR VARCHAR(20),
    CORREO_ELECTRONICO VARCHAR(150),
    GRADO_INSTRUCCION VARCHAR(100),
    LENGUA_HABITUAL VARCHAR(100),
    RELACION_JEFE_FAMILIA VARCHAR(50),
    TIPO_DE_DOCUMENTO_JEFE_DE_FAMILIA VARCHAR(50),
    DNI_JEFE_FAMILIA VARCHAR(15),
    APELLIDO_PATERNO_JEFE_FAMILIA VARCHAR(100),
    APELLIDO_MATERNO_JEFE_FAMILIA VARCHAR(100),
    NOMBRES_JEFE_FAMILIA VARCHAR(150),
    ESTADO_REGISTRO VARCHAR(50),
    FECHA_CREACION VARCHAR(100),
    USUARIO_CREA VARCHAR(100),
    FECHA_MODIFICACION VARCHAR(100),
    USUARIO_MODIFICA VARCHAR(100),
    ENTIDAD VARCHAR(150),
    TIPO_REGISTRO VARCHAR(50),
    FECHA_CORTE DATE,
    FECHA_NAC_DATE DATE,
    [EDAD DEL MENOR] VARCHAR(20),
    EDAD_AÑO INT,
    EDAD_MES INT,
    EDAD_DIA INT
);


use [BD_HISINDICADORES]
BULK INSERT dbo.PN_MAYO_2025
FROM 'C:\Users\PC01\Documents\FED\2025_PN_Mayo-IIEE-PACTO REGIONAL.csv'
WITH (
    FIRSTROW = 2,  -- Omitir encabezado
    FIELDTERMINATOR = ';',
    ROWTERMINATOR = '\n',
    CODEPAGE = '65001', -- ansi acp
    TABLOCK
);


use [BD_HISINDICADORES]
select * from [dbo].[PN_MAYO_2025]
select top 10  * from PN_MAYO_2025
where 
	DNI is not null and
	EDAD_LETRAS IN (


SELECT TOP 20 EDAD_LETRAS, COUNT(*) AS total
FROM PN_MAYO_2025
WHERE DNI IS NOT NULL 
AND EDAD_LETRAS not IN ('"4 año(s), 3 mes(es), 26 dia(s)"')
--and EDAD_LETRAS is not null
GROUP BY EDAD_LETRAS
ORDER BY total DESC

drop table #Temp_nominal

SELECT COUNT(DNI) AS total, distrito
--INTO #Temp_nominal
FROM PN_MAYO_2025
where EDAD_LETRAS not like '"4 año(s), 3 mes(es)%"' 
and EDAD_LETRAS not like '"4 año(s), 4 mes(es)%"' 
and EDAD_LETRAS not like '"4 año(s), 5 mes(es)%"'
--and DISTRITO in ('ACO','CHACAPALPA','COMAS','HUAMANCACA CHICO','HUAYUCACHI','HUÁCHAC','JARPA','MANZANARES','NUEVE DE JULIO','PAMPA HERMOSA','QUICHUAY','QUILCAS','RÍO NEGRO','SAN JUAN DE JARPA','SAN PEDRO DE SAÑO','SANTA ROSA DE OCOPA','SAPALLANGA','TRES DE DICIEMBRE','VIZCATAN DEL ENE','VÍQUES','YANACANCHA','YAUYOS')
and DNI is not null
GROUP BY DISTRITO
ORDER BY DISTRITO

select * from #Temp_nominal


drop table #Temp_homologados
go
SELECT COUNT(DNI) AS total, distrito
INTO #Temp_homologados
FROM PN_MAYO_2025
where EDAD_LETRAS not like '"4 año(s), 3 mes(es)%"' 
and EDAD_LETRAS not like '"4 año(s), 4 mes(es)%"' 
and EDAD_LETRAS not like '"4 año(s), 5 mes(es)%"'
and DISTRITO in ('ACO','CHACAPALPA','COMAS','HUAMANCACA CHICO','HUAYUCACHI','HUÁCHAC','JARPA','MANZANARES','NUEVE DE JULIO','PAMPA HERMOSA','QUICHUAY','QUILCAS','RÍO NEGRO','SAN JUAN DE JARPA','SAN PEDRO DE SAÑO','SANTA ROSA DE OCOPA','SAPALLANGA','TRES DE DICIEMBRE','VIZCATAN DEL ENE','VÍQUES','YANACANCHA','YAUYOS')
and DNI is not null
and CODIGO_INSTITUCION_EDUCATIVA IS NOT NULL
GROUP BY DISTRITO
ORDER BY DISTRITO


select #Temp_nominal.DISTRITO, #Temp_nominal.total as 'nominal',
#Temp_homologados.total as 'homologados'
from #Temp_homologados  right join #Temp_nominal
on #Temp_homologados.DISTRITO=#Temp_nominal.DISTRITO


select CODIGO_INSTITUCION_EDUCATIVA, count(*) from [PN_MAYO_2025]
where CODIGO_INSTITUCION_EDUCATIVA is null
group by  CODIGO_INSTITUCION_EDUCATIVA 

select DNI, NOMBRE_NINO, APELLIDO_PATERNO, APELLIDO_MATERNO,
FECHA_NACIMIENTO, EDAD_LETRAS, DISTRITO, NOMBRE_INSTITUCION_EDUCATIVA,
CODIGO_INSTITUCION_EDUCATIVA from PN_MAYO_2025
where
EDAD_LETRAS not like '"4 año(s), 3 mes(es)%"' 
and EDAD_LETRAS not like '"4 año(s), 4 mes(es)%"' 
and EDAD_LETRAS not like '"4 año(s), 5 mes(es)%"'
--and DISTRITO in ('ACO','CHACAPALPA','COMAS','HUAMANCACA CHICO','HUAYUCACHI','HUÁCHAC','JARPA','MANZANARES','NUEVE DE JULIO','PAMPA HERMOSA','QUICHUAY','QUILCAS','RÍO NEGRO','SAN JUAN DE JARPA','SAN PEDRO DE SAÑO','SANTA ROSA DE OCOPA','SAPALLANGA','TRES DE DICIEMBRE','VIZCATAN DEL ENE','VÍQUES','YANACANCHA','YAUYOS')
and DNI is not null
order by PN_MAYO_2025.DISTRITO asc